apiVersion: aws.platformref.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: platform-ref-aws
  namespace: default
  annotations:
    uptest.upbound.io/pre-delete-hook: testhooks/delete-release.sh
spec:
  id: platform-ref-aws
  parameters:
    version: "1.26"
    nodes:
      count: 3
      size: small
    services:
      operators:
        prometheus:
          version: "34.5.1"
        universal-crossplane:
          version: "1.12.1-up.1"
  writeConnectionSecretToRef:
    name: platform-ref-aws-kubeconfig
